name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java

on:
  pull_request:
  push:
    branches: [ "main" ]
    tags: [ "*" ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache Scala dependencies
        uses: coursier/cache-action@v6
      - name: Check code formatting
        run: ./sbt check
