name: Deploy client to AWS

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::195175520793:role/lambdaworks-bot-github-actions
          aws-region: us-east-1

      - name: Deploy to Amazon ECS service
        run: aws s3 sync /home/runner/work/lambda-knowledge-bot/lambda-knowledge-bot/client/dist/ s3://knowle
