name: Deploy client to AWS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::195175520793:role/lambdaworks-bot-github-actions
          aws-region: us-east-1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set env
        run: |
          cd ${{ secrets.CLIENT_PATH }}
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_FRONT_URL=${{ secrets.VITE_FRONT_URL }}" >> .env
          echo "VITE_CLIENT_ID=${{ secrets.VITE_CLIENT_ID }}" >> .env
          echo "VITE_DOMAINE=${{ secrets.VITE_DOMAINE }}" >> .env
          echo "VITE_STAGE=${{ secrets.VITE_STAGE }}" >> .env
          source .env

      - name: Install yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update && sudo apt install yarn -y

      - name: Build app
        run: |
          cd ${{ secrets.CLIENT_PATH }}
          yarn install
          yarn vite build

      - name: Deploy to S3
        run: aws s3 sync ${{ secrets.CLIENT_PATH }}/dist/ s3://${{ secrets.BUCKET }}